name: Makefile CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    #- name: setup
    #  run: ls /usr/local
      
    - name: install csh
      run: brew install tcsh
      
    #- name: check tcsh
    #  run: ls /home/linuxbrew/.linuxbrew/bin
      
    #- name: check 
    #  run: ls /usr/local/sbin
      
    #- name: check
    #  run: ls /usr
      
    #- name: check
    #  run: ls /usr/local/opt
      
    #- name: csh
    #  run: ls /bin && ls /usr/bin
      
    #- name: verlist
    #  run: cd test/wave && $GITHUB_WORKSPACE/util/verlist output.R 0 0
      
    - name: install
      run: brew install openblas # arpack
      
    - name: Add util to path
      run: echo "$GITHUB_WORKSPACE/util" >> $GITHUB_PATH
      
    - name: build slatec
      run: cd slatec/src && make && make install
      
    - name: build util
      run: cd util && ln -s gcc.mak Makefile && make
      
    - name: configure LNS3d
      run: cd src && ln -s gcc.mak Makefile
      
    - name: build LNS3d
      run: cd src && make CC=gcc
      
    #- name: set path
    #  run: export PATH=$PATH:`pwd`/util && echo $PATH
      
    - name: Run test
      run: cd test/wave && ./run.sh
      
    - name: Run 2d
      run: cd test/2d && env ./run.sh
      
    #- name: Run distcheck
    #  run: make distcheck
