name: Makefile CI MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    #- name: setup
    #  run: ls /usr/local
      
    #- name: check gfortran
    #  run: ls /usr/local/bin
      
    - name: install tcsh
      run: brew install tcsh
      
    #- name: check tcsh
    #  run: ls /usr/local/bin
      
    - name: print Github environment
      run: env | sort
      
    #- name: check
    #  run: echo "{path}" >> $GITHUB_PATH
      
    - name: Add util to path
      run: echo "$GITHUB_WORKSPACE/util" >> $GITHUB_PATH
      
    - name: echo paths
      run: echo $HOME && echo $GITHUB_WORKSPACE && echo $PATH
      
    - name: verify verlist
      run: cd test/wave && $GITHUB_WORKSPACE/util/verlist output.R 0 0
      shell: tcsh {0}
      
    #- name: install
    #  run: brew install gcc openblas arpack
      
    - name: build slatec
      run: cd slatec/src && make FC=gfortran-11 && make FC=gfortran-11 CC=gcc-11 install
      
    - name: build util
      run: cd util && ln -s gcc.mak Makefile && make FC=gfortran-11 CC=gcc-11 F77=gfortran-11
      
    - name: configure LNS3d
      run: cd src && ln -s gcc.mak Makefile
      
    - name: build LNS3d
      run: cd src && make CC=gcc FC=gfortran-11 CC=gcc-11 F77=gfortran-11
      
    #- name: set path
    #  run: export PATH=$PATH:`pwd`/util && echo $PATH
      
    #- name: echo path
    #  run:  echo "$HOME/lns3d/util" >> $GITHUB_PATH
      
    - name: Run wave test
      run: cd test/wave && ./run.sh
      
    - name: Run 2d test
      run: cd test/2d && ./run.sh
