name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup
      run: ls /usr/local
      
    - name: check
      run: ls /usr/local/opt
      
    - name: configure
      #run: ./configure
      run: cd src && ln -s gcc.mak Makefile
      
    - name: Install dependencies
      run: cd src && make COMP_CC=gcc
      
    #- name: Run check
      #run: make check
      
    #- name: Run distcheck
      #run: make distcheck
