name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup
      run: ls /usr/local
      
    - name: check
      run: ls /usr/local/lib
      
    - name: install
      run: brew install openblas arpack
      
    - name: build slatec
      run: cd slatec/src && make && make install
      
    - name: build util
      run: cd util && ln -s gcc.mak Makefile && make
      
    - name: configure LNS3d
      run: cd src && ln -s gcc.mak Makefile
      
    - name: build LNS3d
      run: cd src && make COMP_CC=gcc
      
    - name: set path
      run: export PATH=$PATH:`pwd`/util && echo $PATH
      
    - name: Run test
      run: cd test/wave && env PATH=$PATH:../../util ./run.sh
      
    #- name: Run distcheck
      #run: make distcheck
